# Generated by Django 5.2.5 on 2025-08-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_category_alter_product_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'カテゴリ'},
        ),
    ]
