# Generated by Django 5.2.5 on 2025-08-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ一覧'},
        ),
    ]
