# Generated by Django 5.2.5 on 2025-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='商品詳細'),
        ),
    ]
