# Generated by Django 5.2.5 on 2025-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='商品詳細の説明'),
        ),
    ]
