# Generated by Django 5.2.5 on 2025-09-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('R1', 'Rank 1'), ('R2', 'Rank 2'), ('R3', 'Rank 3')], max_length=2)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='game.skillbook')),
            ],
            options={
                'unique_together': {('book', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='SkillEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('DAMAGE', 'Damage'), ('HEAL', 'Heal'), ('POISON', 'Poison'), ('ATK_BUFF', 'Atk Buff'), ('DEF_BUFF', 'Def Buff')], max_length=10)),
                ('target_side', models.CharField(choices=[('SELF', 'Self'), ('OPP', 'Opp'), ('ALL', 'All')], max_length=4)),
                ('target_stat', models.CharField(choices=[('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('HP_CURR', 'Hp Curr'), ('HP_MAX', 'Hp Max')], max_length=16)),
                ('value_base', models.IntegerField(default=0)),
                ('value_terms', models.JSONField(blank=True, default=list)),
                ('remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='game.skillvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
