# Generated by Django 5.2.5 on 2025-09-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilleffect',
            name='value_terms',
        ),
        migrations.CreateModel(
            name='SkillEffectTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_side', models.CharField(choices=[('SELF', 'Self'), ('OPP', 'Opp'), ('ALL', 'All')], max_length=4)),
                ('ref_stat', models.CharField(choices=[('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('HP_CURR', 'Hp Curr'), ('HP_MAX', 'Hp Max')], max_length=16)),
                ('scale', models.FloatField()),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='game.skilleffect')),
            ],
            options={
                'verbose_name': 'Value term',
                'verbose_name_plural': 'Value terms',
            },
        ),
    ]
