# Generated by Django 5.2.5 on 2025-08-20 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='値段')),
                ('description', models.TextField(blank=True, verbose_name='商品詳細')),
            ],
            options={
                'ordering': ['price'],
                'indexes': [models.Index(fields=['is_active'], name='shops_item_is_acti_1132ab_idx')],
            },
        ),
    ]
